default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        args: [ '--disable-telemetry' ]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^dotfiles/common/.config/ranger

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ fix, feat, chore, docs, feat!, chore!, fix! ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .markdownlint.yaml
          - --fix
