version: '3'

includes:
  brew: "./taskfiles/taskfile.brew.yml"
  gotask: "./taskfiles/taskfile.gotask.yml"
  foundry: "./taskfiles/taskfile.foundry.yml"
  helper: "./taskfiles/taskfile.helper.yml"
  linux: "./taskfiles/taskfile.linux.yml"
  macos: "./taskfiles/taskfile.macos.yml"
  poetry: "./taskfiles/taskfile.poetry.yml"
  precommit: "./taskfiles/taskfile.precommit.yml"
  python: "./taskfiles/taskfile.python.yml"
  sdkman: "./taskfiles/taskfile.sdkman.yml"
  stow: "./taskfiles/taskfile.stow.yml"
  submodules: "./taskfiles/taskfile.submodules.yml"
  zimfw: "./taskfiles/taskfile.zimfw.yml"
  zsh: "./taskfiles/taskfile.zsh.yml"

tasks:

  default:
    desc: Default
    cmds:
      - |
        echo "Home dir: {{.HOME}}"
        echo "Root dir: {{.ROOT_DIR}}"
        echo "Working dir: {{.USER_WORKING_DIR}}"
        echo "OS: {{OS}}"
        task --list
    silent: true

  setup:
    desc: Poetry and pre-commit setup
    cmds:
      - task: poetry:setup
      - task: precommit:setup

  update:
    desc: Poetry and pre-commit update
    cmds:
      - task: poetry:update
      - task: precommit:update

  pcrun:
    aliases: [run]
    desc: Run pre-commit on all files
    cmds:
      - task: precommit:run

  os-update:
    aliases: [os]
    desc: Update and refresh system
    cmds:
      - task: macos:update
      - task: linux:update
