version: '3'

tasks:

  default:
    internal: true
    desc: Default
    cmds:
      - |
        echo "Working dir: {{.USER_WORKING_DIR}}"
        echo "OS: {{OS}}"
        task --list
    silent: true

  assert:
    cmds:
      - for:
          var: REQUIRED_TOOLS
          split: ','
          as: TOOL
        cmd: |
          [ -n "$(which {{ .TOOL }})" ] || ( \
            echo "ERROR: `{{ .TOOL }}` not found" && exit 1; \
          )
    silent: true
    internal: true
    vars:
      REQUIRED_TOOLS: pacman, yay

  setup:
    deps: [assert]
    internal: true
    desc: Install linux
    platforms: [linux]
    cmds:
      - task: config
      - task: productivity
      - task: :submodules:init
      - task: :zimfw:install
      - task: :zsh:shell

  config:
    deps: [assert]
    internal: true
    desc: Install development packages
    platforms: [linux]
    vars:
      CONFIG: "{{.HOME}}/.config"
      EXTRAS: "{{.ROOT_DIR}}/installation/linux/extras"
    cmds:
      - mkdir -p "{{.CONFIG}}/gtk-3.0"
      - mkdir -p "{{.HOME}}/.local/bin"
      - rm -rf "{{.CONFIG}}/mimeapps.list"
      - cp "{{.EXTRAS}}/mimeapps.list" "{{.CONFIG}}"
      - rm -rf "{{.HOME}}/user-dirs"
      - cp "{{.EXTRAS}}/user-dirs.dirs" "{{.CONFIG}}"

  productivity:
    deps: [assert]
    internal: true
    desc: Install development packages
    platforms: [linux]
    cmds:
      - "{{.ROOT_DIR}}/installation/linux/07-productivity.sh"
